# Generated by Django 4.2.30 on 2026-04-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('patient_id', models.CharField(max_length=255)),
                ('reading', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadingDeDupKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReadingDeDupKey', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
