# Generated by Django 4.2.30 on 2026-04-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255, unique=True)),
                ('low_threshold_glucose_mgdl', models.FloatField()),
                ('high_threshold_glucose_mgdl', models.FloatField()),
            ],
        ),
    ]
